prgrms-web-devcourse/Team_Coco_Be

src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/Memo.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/Voting.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContent.java, src/main/java/com/cocodan/triplan/schedule/domain/vo/Tag.java
- 메모
- 체크리스트
- 투표
- 태그
엔티티 생성
tostring, equals and hashcode 를 재정의하긴 했는데, 다른 분들은 어떤 방식으로 재정의 하시나요?
=> [TP-10] 메모, 체크리스트, 투표, 태그 엔티티 생성

src/main/java/com/cocodan/triplan/common/BaseEntity.java, src/main/java/com/cocodan/triplan/common/error/NotExistsException.java, src/main/java/com/cocodan/triplan/config/JpaConfig.java, src/main/java/com/cocodan/triplan/member/domain/Member.java, src/main/java/com/cocodan/triplan/member/domain/vo/GenderType.java, src/main/java/com/cocodan/triplan/util/BaseEntity.java
- Member Entity 생성
- Entity 생성 정보를 저장하는 BaseEntity
- 에러 정의 클래스 NotExistsException
- Member의 성별 타입을 정의하는 VO GenderType
=> [TP-41]Feature: Member Entity 및 Common BaseEntity 구현

src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/Memo.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/Voting.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContent.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ChecklistCreation.java, src/main/java/com/cocodan/triplan/schedule/dto/request/MemoCreation.java, src/main/java/com/cocodan/triplan/schedule/dto/request/VotingCreation.java, src/main/java/com/cocodan/triplan/schedule/repository/ChecklistRepository.java, src/main/java/com/cocodan/triplan/schedule/repository/MemoRepository.java, src/main/java/com/cocodan/triplan/schedule/repository/VotingRepository.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
원래는 Root Entity의 Repository 하나로 관리하려 했지만 구현 상의 문제로
메모, 체크리스트, 투표 각각의 Repsitory를 따로 만들었습니다.
=> [TP-13] 일정에 메모, 체크리스트, 투표 추가

src/main/java/com/cocodan/triplan/converter/ScheduleConverter.java, src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ChecklistCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/DailyScheduleSpotCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/MemoCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleModification.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleModificationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/VotingCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleDetailResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleSimpleResponse.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
- 장소와 관련된 수정 삭제 입니다.
- 메모, 투표, 체크리스트는 따로 PR을 분리할 예정입니다.
=> [TP-19] 여행 일정 수정,삭제

src/main/java/com/cocodan/triplan/member/service/MemberService.java, src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java, src/main/java/com/cocodan/triplan/post/schedule/dto/request/SchedulePostCreatieRequest.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostCreateResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostResponse.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostService.java, src/main/java/com/cocodan/triplan/spot/domain/vo/City.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
=> [TP-32] 여행 공유 게시글 작성 기능 추가

src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/Memo.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/dto/request/MemoRequest.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
- 메모는 수정 및 삭제
- 체크리스트는 선택,해제 및 삭제
=> [TP-44] 메모, 체크리스트 수정 및 삭제

src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/Voting.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContent.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContentMember.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingMember.java, src/main/java/com/cocodan/triplan/schedule/dto/request/VotingRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/response/MemoResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/VotingSimpleResponse.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
투표 하는거 로직이 생각보다 어렵네요..
투표에 현재 참여한 사람 수도 구해야 되고,
항목 별로도 누가 투표했는지, 몇 명이나 투표했는지 구하는 부분이 좀 힘들었는데. 로직에 대해 많은 의견 부탁드려요.
=> [TP-45] 투표 행사 및 삭제

pom.xml, src/main/java/com/cocodan/triplan/config/SwaggerConfig.java, src/main/java/com/cocodan/triplan/config/WebSecurityConfig.java, src/main/java/com/cocodan/triplan/member/controller/MemberController.java, src/main/java/com/cocodan/triplan/member/dto/request/MemberCreateRequest.java, src/main/java/com/cocodan/triplan/member/dto/request/MemberDeleteRequest.java, src/main/java/com/cocodan/triplan/member/dto/request/MemberGetOneRequest.java, src/main/java/com/cocodan/triplan/member/dto/request/MemberUpdateRequest.java
Api 테스트할 수 있는 Swagger 설정
MemberController 작업 내용 CRUD Api 설정
=> [TP-25]Feature: Member Service CRUD 구현 및 테스트 작성

pom.xml, src/main/java/com/cocodan/triplan/config/WebSecurityConfig.java, src/main/java/com/cocodan/triplan/member/dto/request/MemberCreateRequest.java, src/main/resources/META-INF/MANIFEST.MF, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
=> [TP-57] 빌드 및 배포 테스트

src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/DailyScheduleSpot.java, src/main/java/com/cocodan/triplan/schedule/domain/Memo.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/ScheduleMember.java, src/main/java/com/cocodan/triplan/schedule/domain/ScheduleTheme.java, src/main/java/com/cocodan/triplan/schedule/domain/Voting.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContent.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContentMember.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/java/com/cocodan/triplan/spot/domain/Spot.java
- 스웨거 적용하고 ResponseEntity static method로 반환했습니다.
- 엔티티에 extends BaseEntity 상속 안 했던거 하는걸로 바꿨습니다.
- Spot에 Persistable 구현하여 isNew 메소드 사용했습니다.
=> [TP-59] 스웨거 적용 및 컨트롤러에서 ResponseEntity의 static method로 반환하기

src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
* 게시글 생성, 수정 요청 dto 이름 변경
* schedule service의 일정 생성 메서드 이름 변경
=> [TP-37] Fix: 누락된 수정사항 반영

src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java
* SchedulePostController에 Swagger 적용을 위한 Annotation 부착
* 서버상에서의 테스트를 위해 유저 인증 정보 임시로 comment-out
=> [TP-68] Feature: Swagger 적용 및 테스를 위한 임시 comment-out

src/main/java/com/cocodan/triplan/TriplanApplication.java, src/main/java/com/cocodan/triplan/exception/ExceptionResponse.java, src/main/java/com/cocodan/triplan/exception/GlobalExceptionHandler.java, src/main/java/com/cocodan/triplan/exception/common/ForbiddenException.java, src/main/java/com/cocodan/triplan/exception/common/NotFoundException.java, src/main/java/com/cocodan/triplan/exception/common/NotIncludeException.java, src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/Memo.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/Voting.java, src/main/java/com/cocodan/triplan/schedule/domain/VotingContent.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ChecklistCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/DailyScheduleSpotCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/MemoRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleModificationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/VotingCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/VotingRequest.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/java/com/cocodan/triplan/spot/domain/Spot.java, src/main/java/com/cocodan/triplan/util/ExceptionMessageUtils.java, src/main/resources/exceptions.properties, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
- 공통 예외 응답 클래스 생성
- Bean Validation 추가
- ExceptionMesssageUtils, exception.properties 추가
=> [TP-48] 예외처리

src/main/java/com/cocodan/triplan/exception/common/ForbiddenException.java, src/main/java/com/cocodan/triplan/exception/common/NotFoundException.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostResponse.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostService.java, src/main/java/com/cocodan/triplan/schedule/domain/Checklist.java, src/main/java/com/cocodan/triplan/schedule/domain/Schedule.java, src/main/java/com/cocodan/triplan/schedule/domain/ScheduleTheme.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ChecklistCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/DailyScheduleSpotCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/request/ScheduleModificationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ChecklistResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleSimpleResponse.java, src/main/java/com/cocodan/triplan/schedule/repository/ScheduleRepository.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/java/com/cocodan/triplan/spot/domain/Spot.java, src/main/java/com/cocodan/triplan/spot/dto/response/SpotResponse.java, src/main/resources/exceptions.properties, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
- 체크리스트 날짜 LocalDate 타입의 date -> 날짜 순서인 int 타입 day 로 변경
- 필드명 변경
- Thema -> Themes 로 변경
- 예외 메시지 변경 및 도메인 별 메시지 추가 (ex) Member : 회원, Schedule : 일정 등
=> [TP-74] 일정 request, response 응답 제약조건과 데이터 필드명 변경

src/main/java/com/cocodan/triplan/exception/ExceptionResponse.java, src/main/java/com/cocodan/triplan/exception/GlobalExceptionHandler.java, src/main/java/com/cocodan/triplan/exception/common/ForbiddenException.java, src/main/java/com/cocodan/triplan/schedule/dto/response/VotingDetailResponse.java, src/main/java/com/cocodan/triplan/schedule/repository/ScheduleRepository.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/resources/exceptions.properties
- Feature : 투표 복수 선택 가능 여부 응답 추가
- 서비스 코드에서 검증 부분 리팩토링
- 예외 발생시 로깅 및 전체 예외 메시지 추가
검증 로직
1. Schedule 이 존재하는지 검증
2. 하위 엔티티 (메모, 체크리스트, 투표) 가 존재하는지 검증
3. 하위 엔티티의 id가 Schedule에 속해 있는 것이 맞는지 검증
4. 접근하려는 멤버가 조회,수정,삭제의 권한이 있는지 검증
=> [TP-75] 일정 CRUD 로직 리팩토링

src/main/java/com/cocodan/triplan/TriplanApplication.java, src/main/java/com/cocodan/triplan/aop/aspect/LogTraceAspect.java, src/main/java/com/cocodan/triplan/aop/aspect/Pointcuts.java, src/main/java/com/cocodan/triplan/aop/logtrace/LogTrace.java, src/main/java/com/cocodan/triplan/aop/logtrace/ThreadLocalLogTrace.java, src/main/java/com/cocodan/triplan/aop/logtrace/TraceId.java, src/main/java/com/cocodan/triplan/aop/logtrace/TraceStatus.java, src/main/resources/logback.xml
비즈니스 로직 파일로 로그 남기기
로깅 내용 ( 사용자 id, 호출한 메소드, 소요 시간)
현재는 사용자 id 대신 anonymous로 출력하는 상황입니다.
=> [TP-80] 비즈니스 로직 로깅

src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java, src/main/java/com/cocodan/triplan/post/schedule/domain/SchedulePostNestedComment.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostDetailResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostNestedCommentResponse.java, src/main/java/com/cocodan/triplan/post/schedule/repository/SchedulePostNestedCommentRepository.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostService.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
* 혼란이 생기지 않게 TP-66번 머지된 이후에 PR 작성하려 하였으나 리뷰가 너무 지연되어서 미리 전부 올려둡니다.
* 현재 이 PR에 TP-66번에 대한 커밋도 같이 올라가 있는데, TP-66번 PR이 리뷰 완료 및 머지되는 대로 rebase 할 예정입니다.
=> [TP-77] 대댓글 조회, 작성 기능 구현

src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java, src/main/java/com/cocodan/triplan/post/schedule/dto/request/SchedulePostCommentRequest.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostService.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
* 혼란이 생기지 않게 TP-66번 및 쎼-77번이 머지된 이후에 PR 작성하려 하였으나 리뷰가 너무 지연되어서 미리 전부 올려둡니다.
* 현재 이 PR에 이전 이슈들에 대한 커밋도 같이 올라가 있는데, 이전 PR들이 리뷰 완료 및 머지되는 대로 rebase 할 예정입니다.
=> [TP-84] 대댓글 수정, 삭제 기능 구현

src/main/java/com/cocodan/triplan/schedule/controller/ScheduleController.java, src/main/java/com/cocodan/triplan/schedule/domain/DailyScheduleSpot.java, src/main/java/com/cocodan/triplan/schedule/dto/request/DailyScheduleSpotCreationRequest.java, src/main/java/com/cocodan/triplan/schedule/dto/response/DailyScheduleSpotResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/IdResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleDetailResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleSpotResponse.java, src/main/java/com/cocodan/triplan/schedule/repository/ScheduleRepository.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/java/com/cocodan/triplan/spot/dto/response/SpotResponse.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java, src/test/java/com/cocodan/triplan/schedule/service/ScheduleServiceTest.java
- 장소의 날짜 필드 LocalDate -> int 로 변경 (순서의 의미)
- id 응답 Long이 아닌 dto로 래핑. 좌표 응답 Position으로 래핑
=> [TP-90] 일정 도메인 데이터 프론트와 협의

src/main/java/com/cocodan/triplan/config/WebSecurityConfigure.java, src/main/java/com/cocodan/triplan/friend/controller/FriendController.java, src/main/java/com/cocodan/triplan/friend/domain/Friend.java, src/main/java/com/cocodan/triplan/friend/dto/request/FriendRequest.java, src/main/java/com/cocodan/triplan/friend/repository/FriendRepository.java, src/main/java/com/cocodan/triplan/friend/service/FriendService.java, src/main/java/com/cocodan/triplan/member/controller/MemberController.java, src/main/java/com/cocodan/triplan/member/repository/MemberRepository.java, src/main/java/com/cocodan/triplan/member/service/MemberService.java, src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java, src/main/java/com/cocodan/triplan/post/schedule/repository/CustomSchedulePostRepository.java, src/main/java/com/cocodan/triplan/post/schedule/repository/CustomSchedulePostRepositoryImpl.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostSearchService.java, src/test/java/com/cocodan/triplan/member/service/MemberServiceTest.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
친구 도메인 기능
Page -> List로 반환
순환 참조 문제 해결
=> [TP-89] 친구 도메인 CRUD

src/main/java/com/cocodan/triplan/post/schedule/controller/SchedulePostController.java, src/main/java/com/cocodan/triplan/post/schedule/domain/Like.java, src/main/java/com/cocodan/triplan/post/schedule/domain/SchedulePost.java, src/main/java/com/cocodan/triplan/post/schedule/domain/SchedulePostComment.java, src/main/java/com/cocodan/triplan/post/schedule/domain/SchedulePostNestedComment.java, src/main/java/com/cocodan/triplan/post/schedule/dto/request/SchedulePostCommentRequest.java, src/main/java/com/cocodan/triplan/post/schedule/dto/request/SchedulePostLikeRequest.java, src/main/java/com/cocodan/triplan/post/schedule/dto/request/SchedulePostRequest.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostCommentResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostCreateResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostDetailResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostNestedCommentResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostResponse.java, src/main/java/com/cocodan/triplan/post/schedule/repository/SchedulePostLikeRepository.java, src/main/java/com/cocodan/triplan/post/schedule/repository/SchedulePostNestedCommentRepository.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostSearchService.java, src/main/java/com/cocodan/triplan/post/schedule/service/SchedulePostService.java, src/test/java/com/cocodan/triplan/post/schedule/service/SchedulePostServiceTest.java
* Entity, Dto의 필드에 대한 검증을 붙였습니다.
* Service에서 중복되는 코드들을 뽑아서 분리했습니다.
* 일부 불필요한 인자를 받는 부분들을 제거하였습니다.
=> [TP-78] Entity, DTO 리팩터링

src/main/java/com/cocodan/triplan/schedule/domain/DailyScheduleSpot.java, src/main/java/com/cocodan/triplan/schedule/dto/response/DailyScheduleSpotResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleSpotResponse.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/resources/sql/data_new.sql, src/main/resources/sql/schema_new.sql, src/test/resources/sql/data_new.sql, src/test/resources/sql/schema_new.sql
- data.sql 수정
- 여행 장소 필드에 placeName 추가 
- dto에 검증 애노테이션 리팩토링
=> [TP-97] DTO 검증 리팩토링

src/main/java/com/cocodan/triplan/friend/service/FriendService.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostCommentResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostDetailResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostNestedCommentResponse.java, src/main/java/com/cocodan/triplan/post/schedule/dto/response/SchedulePostResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleDetailResponse.java, src/main/java/com/cocodan/triplan/schedule/dto/response/ScheduleSimpleResponse.java
formId, toId 순서 변경
LocalDate 응답 -> String
일정 상세 조회 기능에서 imageUrl도 리턴
=> [TP-101] 친구 도메인 리팩토링

src/main/java/com/cocodan/triplan/exception/GlobalExceptionHandler.java, src/main/java/com/cocodan/triplan/friend/domain/Friend.java, src/main/java/com/cocodan/triplan/friend/domain/vo/FriendId.java, src/main/java/com/cocodan/triplan/friend/repository/FriendRepository.java, src/main/java/com/cocodan/triplan/friend/service/FriendService.java, src/main/java/com/cocodan/triplan/member/repository/MemberRepository.java, src/main/java/com/cocodan/triplan/schedule/service/ScheduleService.java, src/main/resources/exceptions.properties, src/main/resources/sql/schema_new.sql, src/test/resources/sql/schema_new.sql
- 친구 테이블 복합키로 변경.
- 여행 멤버 CRUD시 버그 수정
=> [TP-109] 친구 여러번 되는 버그 수정, 여행 멤버 추가 버그 수정

src/main/java/com/cocodan/triplan/common/AuditorAwareImpl.java
=> Fix : AuditorAware anonymous일 때 발생하는 에러 수정
